vector_store:
  type: "milvus"
  milvus:
    host: "localhost"
    port: 19530
    collection_name: "contract_clauses"
  faiss:
    index_path: "data/faiss_index"

graph_store:
  type: "neo4j"
  neo4j:
    uri: "bolt://your_ip:7687"
    username: "neo4j"
    password: "your_passward"
