llm:
  model_name: "model_name"
  temperature: 0.0
  api_key: "api_key"
  base_url: "base_url"
  providers: "openai"

embeddings:
  model_name: "text-embedding-3-small"
  provider: "openai"
  chunk_size: 1000
  chunk_overlap: 200
