spring:
  application:
    name: cra-contract-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: contract-compliance-agent
      config:
        server-addr: localhost:8848
        namespace: contract-compliance-agent
        group: DEFAULT_GROUP
        file-extension: yml
        import-check:
          enabled: false   # 关闭 spring.config.import 检查
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://your_ap:5432/contract_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      host: your_ap
      port: 27017
      database: contract_content
  rabbitmq:
    host: your_ap
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
  elasticsearch:
    uris: http://your_ap:9200

# SFTP和SSH 配置
remote:
  host: your_ap
  port: 22
  username: 202312150002
  password: 20001017aA@
  # 合同文件存储路径
  upload-path: /data1/nuist_llm/java-project/cra/files/contracts
  # OCR结果输出路径
  ocr-output-path: /data1/nuist_llm/java-project/cra/files/contracts/ocr_result
  # Mineru命令路径
  mineru-command: mineru

ftp:
  host: 172.27.192.1
  port: 1007
  username: anonymous
  password: 
  base-path: /contracts

logging:
  level:
    org.apache.pdfbox: ERROR
    org.apache.fontbox: ERROR

server:
  port: 8082 # 合同服务端口

# Python AI 服务配置
python-service:
  base-url: http://localhost:8000/pycra/v1
